2017-06-22 13:58:38,881 [Thread-17:6020] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /element/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\eclipsworkdir\Automation_Platform\autoDjango\views.py", line 107, in element
    element_list = Project.objects.get(pk=project_id).element_set.all()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Project matching query does not exist.
2017-06-22 13:58:40,211 [Thread-18:9604] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-06-22 13:59:22,549 [Thread-19:1936] [django.request:152] [base:get_response] [WARNING]- Not Found: /element.html
2017-06-22 14:20:56,068 [Thread-35:10952] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /element/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\eclipsworkdir\Automation_Platform\autoDjango\views.py", line 107, in element
    element_list = Project.objects.get(pk=project_id).element_set.all()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Project matching query does not exist.
